# Generated by Django 4.0.4 on 2022-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=255)),
                ('goal', models.PositiveIntegerField(blank=True, null=True)),
                ('date_limit', models.DateField()),
                ('price_per_time', models.IntegerField(blank=True, null=True)),
                ('progress_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
    ]
